
 export const data =[
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Energy",
            "topic": "gas",
            "insight": "Annual Energy Outlook",
            "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
            "region": "Northern America",
            "start_year": "",
            "impact": "",
            "added": "January, 20 2017 03:51:25",
            "published": "January, 09 2017 00:00:00",
            "country": "United States of America",
            "relevance": 2,
            "pestle": "Industries",
            "source": "EIA",
            "title": "U.S. natural gas consumption is expected to increase during much of the projection period.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Energy",
            "topic": "oil",
            "insight": "Annual Energy Outlook",
            "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
            "region": "Northern America",
            "start_year": "",
            "impact": "",
            "added": "January, 20 2017 03:51:24",
            "published": "January, 09 2017 00:00:00",
            "country": "United States of America",
            "relevance": 2,
            "pestle": "Industries",
            "source": "EIA",
            "title": "Reference case U.S. crude oil production is projected to recover from recent declines.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Energy",
            "topic": "consumption",
            "insight": "Annual Energy Outlook",
            "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
            "region": "Northern America",
            "start_year": "",
            "impact": "",
            "added": "January, 20 2017 03:51:23",
            "published": "January, 09 2017 00:00:00",
            "country": "United States of America",
            "relevance": 2,
            "pestle": "Industries",
            "source": "EIA",
            "title": "U.S. petroleum consumption is projected to remain below the 2005 level.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Environment",
            "topic": "oil",
            "insight": "WRI Partnership Aims to Foster Supply Chain Transparency, Zero-Deforestation Strategies",
            "url": "http://www.sustainablebrands.com/news_and_views/supply_chain/sustainable_brands/wri_partnership_aims_foster_supply_chain_transparency",
            "region": "Central America",
            "start_year": "",
            "impact": "",
            "added": "January, 20 2017 03:26:40",
            "published": "January, 18 2017 00:00:00",
            "country": "Mexico",
            "relevance": 3,
            "pestle": "Environmental",
            "source": "sustainablebrands.com",
            "title": "Mars, Unilever, Cargill and Mondelēz are already using GFW Commodities to assess deforestation risks in their palm oil, soy and cocoa supply chains across a collective area of land the size of Mexico.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "",
            "topic": "market",
            "insight": "N-Hexane Market Hit at a CAGR of 5% by 2024 - PMR Report",
            "url": "http://www.sbwire.com/press-releases/n-hexane-market-hit-at-a-cagr-of-5-by-2024-pmr-report-761520.htm",
            "region": "World",
            "start_year": "",
            "impact": "",
            "added": "January, 19 2017 00:55:54",
            "published": "January, 18 2017 00:00:00",
            "country": "",
            "relevance": 2,
            "pestle": "Economic",
            "source": "SBWire",
            "title": "Polymerization will remain top 3 end-users in global n-Hexane Market.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Energy",
            "topic": "oil",
            "insight": "N-Hexane Market Hit at a CAGR of 5% by 2024 - PMR Report",
            "url": "http://www.sbwire.com/press-releases/n-hexane-market-hit-at-a-cagr-of-5-by-2024-pmr-report-761520.htm",
            "region": "World",
            "start_year": "",
            "impact": "",
            "added": "January, 19 2017 00:55:52",
            "published": "January, 18 2017 00:00:00",
            "country": "",
            "relevance": 2,
            "pestle": "Economic",
            "source": "SBWire",
            "title": "High demand for n-Hexane in oil extraction owing to its effectiveness and high yield is expected to propel the global n-Hexane Market.",
            "likelihood": 3
        },
        {
            "end_year": 2027,
            "intensity": 60,
            "sector": "Government",
            "topic": "market",
            "insight": "E-Boats, Anyone? Electric Boat Market To Reach $20 Billion By 2027, According To New Study",
            "url": "https://cleantechnica.com/2017/01/12/e-boats-anyone-electric-boat-market-reach-20b-2027-according-new-study/",
            "region": "",
            "start_year": "",
            "impact": 3,
            "added": "January, 18 2017 02:23:13",
            "published": "January, 13 2017 00:00:00",
            "country": "",
            "relevance": 5,
            "pestle": "Political",
            "source": "CleanTechnica",
            "title": "The market for non-military electric watercraft and marine motors will balloon to over $20 billion worldwide by 2027.",
            "likelihood": 4
        },
        {
            "end_year": 2018,
            "intensity": 16,
            "sector": "Energy",
            "topic": "oil",
            "insight": "Oil prices will be much more volatile in 2017",
            "url": "http://www.news.tracanada.ca/2017/01/16/oil-prices-will-be-much-more-volatile-in-2017/",
            "region": "World",
            "start_year": 2017,
            "impact": "",
            "added": "January, 17 2017 04:19:59",
            "published": "January, 16 2017 00:00:00",
            "country": "",
            "relevance": 4,
            "pestle": "Economic",
            "source": "TRAC News",
            "title": "Global oil prices will witness much more volatility in 2017 even though markets may rebalance in the first half of the year if output cuts pledged by producers are implemented.",
            "likelihood": 4
        },
        {
            "end_year": 2018,
            "intensity": 16,
            "sector": "",
            "topic": "gdp",
            "insight": "IMF affirms Nigeria's recovery from recession, with 0.8% growth forecast",
            "url": "http://www.vanguardngr.com/2017/01/imf-affirms-nigerias-recovery-recession-0-8-growth-forecast/",
            "region": "Western Africa",
            "start_year": 2017,
            "impact": "",
            "added": "January, 17 2017 03:25:45",
            "published": "January, 16 2017 00:00:00",
            "country": "Nigeria",
            "relevance": 4,
            "pestle": "Economic",
            "source": "Vanguard News",
            "title": "Nigeria Gross Domestic Product will grow by 0.8 percent in 2017 and 2.3 percent in 2018.",
            "likelihood": 4
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Aerospace & defence",
            "topic": "war",
            "insight": "Lebanon: No Land for Beginning Politicians",
            "url": "https://www.avimelamed.com/2017/01/07/lebanon-no-land-for-beginning-politicians/",
            "region": "Western Asia",
            "start_year": "",
            "impact": "",
            "added": "January, 17 2017 03:18:22",
            "published": "January, 07 2017 00:00:00",
            "country": "Lebanon",
            "relevance": 2,
            "pestle": "Political",
            "source": "Avi Melamed",
            "title": "A war in Lebanon will increase the already heavy economic burden Saudi Arabia is carrying.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 4,
            "sector": "Manufacturing",
            "topic": "production",
            "insight": "The Slow Road Back: Oil & Gas Industry Outlook for 2017",
            "url": "http://deloitte.wsj.com/riskandcompliance/2017/01/10/the-slow-road-back-oil-gas-industry-outlook-for-2017/",
            "region": "Northern America",
            "start_year": "",
            "impact": "",
            "added": "January, 17 2017 02:21:11",
            "published": "",
            "country": "United States of America",
            "relevance": 2,
            "pestle": "Industries",
            "source": "WSJ",
            "title": "U.S. production could begin to ramp back up following the rig count upturn.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Retail",
            "topic": "export",
            "insight": "The Slow Road Back: Oil & Gas Industry Outlook for 2017",
            "url": "http://deloitte.wsj.com/riskandcompliance/2017/01/10/the-slow-road-back-oil-gas-industry-outlook-for-2017/",
            "region": "Northern America",
            "start_year": "",
            "impact": "",
            "added": "January, 17 2017 02:21:10",
            "published": "",
            "country": "United States of America",
            "relevance": 2,
            "pestle": "Economic",
            "source": "WSJ",
            "title": "More U.S. LNG (liquified natural gas) export capacity is expected to hit the market.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Energy",
            "topic": "oil",
            "insight": "NM oil patch outlook",
            "url": "https://www.abqjournal.com/928238/nm-oil-patch-outlook.html",
            "region": "",
            "start_year": 2017,
            "impact": "",
            "added": "January, 17 2017 01:51:12",
            "published": "January, 16 2017 00:00:00",
            "country": "",
            "relevance": 3,
            "pestle": "Industries",
            "source": "Abq",
            "title": "2017 could be another record-breaking year in oil production.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Energy",
            "topic": "oil",
            "insight": "NM oil patch outlook",
            "url": "https://www.abqjournal.com/928238/nm-oil-patch-outlook.html",
            "region": "",
            "start_year": "",
            "impact": "",
            "added": "January, 17 2017 01:51:10",
            "published": "January, 16 2017 00:00:00",
            "country": "",
            "relevance": 3,
            "pestle": "Industries",
            "source": "Abq",
            "title": "Oil prices could climb above $60 quite rapidly.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 12,
            "sector": "Energy",
            "topic": "oil",
            "insight": "OPEC sees market stability in 2017, Venezuela aims for $70 price",
            "url": "http://www.reuters.com/article/us-venezuela-opec-idUSKBN1502JJ",
            "region": "Eastern Europe",
            "start_year": "",
            "impact": "",
            "added": "January, 17 2017 01:17:33",
            "published": "January, 17 2017 00:00:00",
            "country": "Russia",
            "relevance": 3,
            "pestle": "Industries",
            "source": "Reuters",
            "title": "OPEC, Russia and other non-members of the producer group will curtail oil output by nearly 1.8 million bpd.",
            "likelihood": 4
        },
        {
            "end_year": "",
            "intensity": 16,
            "sector": "Energy",
            "topic": "oil",
            "insight": "Cargill's quest for fish food grows, enriching canola in Montana and growing protein in tank",
            "url": "http://www.startribune.com/cargill-s-quest-for-fish-food-grows-enriching-canola-in-montana-and-growing-protein-in-tank/410681245/",
            "region": "World",
            "start_year": 2019,
            "impact": "",
            "added": "January, 17 2017 00:55:16",
            "published": "January, 14 2017 00:00:00",
            "country": "",
            "relevance": 4,
            "pestle": "Economic",
            "source": "Star Tribune",
            "title": "Industry demand for fish oil will bypass the world's fish oil supply in 2019.",
            "likelihood": 4
        },
        {
            "end_year": 2025,
            "intensity": 9,
            "sector": "Energy",
            "topic": "battery",
            "insight": "How Electric Trucks Will Shape The Auto Transport Industry",
            "url": "http://evobsession.com/electric-trucks-will-shape-auto-transport-industry/",
            "region": "",
            "start_year": "",
            "impact": "",
            "added": "January, 16 2017 05:54:47",
            "published": "January, 10 2017 00:00:00",
            "country": "",
            "relevance": 3,
            "pestle": "Technological",
            "source": "EV Obsession",
            "title": "Experts predict the costs of replacing electric batteries will decrease by 2.5x by 2025.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 16,
            "sector": "Financial services",
            "topic": "",
            "insight": "Energy Roundup",
            "url": "http://newsletters.creamermedia.co.za/p/m/s/twitter/7XjRADu9PZG2CxYa/eFHTX9e0XGozciPE/",
            "region": "World",
            "start_year": 2017,
            "impact": "",
            "added": "January, 16 2017 03:42:24",
            "published": "",
            "country": "",
            "relevance": 4,
            "pestle": "",
            "source": "creamermedia",
            "title": "The global investment cycle will show the first signs of growth in 2017, since 2014, as confidence the oil and gas sector will start to return, with exploration and production spend set to rise by 3% to $450-billion.",
            "likelihood": 4
        },
        {
            "end_year": "",
            "intensity": 4,
            "sector": "Aerospace & defence",
            "topic": "biofuel",
            "insight": "The Peak Oil President?",
            "url": "http://www.resilience.org/stories/2017-01-11/the-peak-oil-president/",
            "region": "World",
            "start_year": "",
            "impact": "",
            "added": "January, 16 2017 02:25:00",
            "published": "January, 11 2017 00:00:00",
            "country": "",
            "relevance": 2,
            "pestle": "Political",
            "source": "Resilience",
            "title": "While in the past decade downturns in output from old oilfields were replaced with new production enabling steady overall conventional oil supplies, replacement of production is much more doubtful in the immediate years ahead.",
            "likelihood": 2
        },
        {
            "end_year": 2040,
            "intensity": 8,
            "sector": "Energy",
            "topic": "oil",
            "insight": "The Peak Oil President?",
            "url": "http://www.resilience.org/stories/2017-01-11/the-peak-oil-president/",
            "region": "Western Asia",
            "start_year": "",
            "impact": "",
            "added": "January, 16 2017 02:24:59",
            "published": "January, 11 2017 00:00:00",
            "country": "Saudi Arabia",
            "relevance": 4,
            "pestle": "Industries",
            "source": "Resilience",
            "title": "By 2040, the world could need to replace over 4 times the current crude oil output of Saudi Arabia (or more than 40 mbd).",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 8,
            "sector": "Financial services",
            "topic": "policy",
            "insight": "World Bank Forecasts Nigeria To Exit Recession In 2017",
            "url": "https://www.thenews.ng/2017/01/world-bank-forecasts-nigeria-to-exit-recession-in-2017/",
            "region": "Central Africa",
            "start_year": "",
            "impact": "",
            "added": "January, 15 2017 05:21:39",
            "published": "January, 13 2017 00:00:00",
            "country": "Angola",
            "relevance": 2,
            "pestle": "Economic",
            "source": "TheNews.NG",
            "title": "Angola is projected to expand at a moderate 1.2 percent pace as high inflation and tight policy continue to weigh on consumption and investment.",
            "likelihood": 4
        },
        {
            "end_year": "",
            "intensity": 16,
            "sector": "",
            "topic": "economy",
            "insight": "World Bank Forecasts Nigeria To Exit Recession In 2017",
            "url": "https://www.thenews.ng/2017/01/world-bank-forecasts-nigeria-to-exit-recession-in-2017/",
            "region": "World",
            "start_year": 2017,
            "impact": "",
            "added": "January, 15 2017 05:21:36",
            "published": "January, 13 2017 00:00:00",
            "country": "",
            "relevance": 4,
            "pestle": "Economic",
            "source": "TheNews.NG",
            "title": "The global economy will accelerate moderately to 2.7 percent in 2017.",
            "likelihood": 4
        },
        {
            "end_year": "",
            "intensity": 16,
            "sector": "Support services",
            "topic": "market",
            "insight": "Paris department stores expect rebound in 2017, growth forecast for luxury markets",
            "url": "http://za.fashionnetwork.com/news/Paris-department-stores-expect-rebound-in-2017-growth-forecast-for-luxury-markets,779908.html",
            "region": "",
            "start_year": 2017,
            "impact": "",
            "added": "January, 15 2017 04:36:06",
            "published": "January, 13 2017 00:00:00",
            "country": "",
            "relevance": 4,
            "pestle": "Economic",
            "source": "FashionNetwork.com",
            "title": "Analysts at Exane BNP Paribas for their part are expecting a rise in demand on the main luxury goods markets in 2017.",
            "likelihood": 4
        },
        {
            "end_year": 2200,
            "intensity": 24,
            "sector": "",
            "topic": "strategy",
            "insight": "Goldman Sachs Maps Out Its Top Ten Market Themes for 2017",
            "url": "https://www.bloomberg.com/news/articles/2016-11-17/goldman-sachs-maps-out-its-top-ten-market-themes-for-2017",
            "region": "Northern America",
            "start_year": 2017,
            "impact": "",
            "added": "January, 15 2017 03:50:31",
            "published": "",
            "country": "United States of America",
            "relevance": 6,
            "pestle": "Organization",
            "source": "Bloomberg Business",
            "title": "Expect that modest improvements in the macroeconomic backdrop will help lift S&P 500 operating EPS by 10 percent to $116 and they have a year-end S&P 500 target of 2200.",
            "likelihood": 4
        },
        {
            "end_year": "",
            "intensity": 16,
            "sector": "Energy",
            "topic": "oil",
            "insight": "Key events for 2017; Global growth conditions continue to improve ,",
            "url": "https://www.yesbank.in/pdf/monthly_market_presentation_january_2017",
            "region": "World",
            "start_year": 2017,
            "impact": "",
            "added": "January, 15 2017 03:07:03",
            "published": "January, 12 2017 00:00:00",
            "country": "",
            "relevance": 4,
            "pestle": "Economic",
            "source": "Yes Bank",
            "title": "Oil prices in 2017 will be a function of producers sticking to the production cuts and recovery in global demand conditions.",
            "likelihood": 4
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Energy",
            "topic": "oil",
            "insight": "Key events for 2017; Global growth conditions continue to improve ,",
            "url": "https://www.yesbank.in/pdf/monthly_market_presentation_january_2017",
            "region": "World",
            "start_year": "",
            "impact": "",
            "added": "January, 15 2017 03:07:02",
            "published": "January, 12 2017 00:00:00",
            "country": "",
            "relevance": 2,
            "pestle": "Economic",
            "source": "Yes Bank",
            "title": "The rise in crude oil prices will play a key role in shaping global inflation dynamics.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Energy",
            "topic": "gas",
            "insight": "Egypt Petroleum Show (EGYPS 2017)",
            "url": "http://www.egyps.com/media/530316/egyps-show-preview-online-8117.pdf",
            "region": "Northern Africa",
            "start_year": "",
            "impact": "",
            "added": "January, 15 2017 03:06:36",
            "published": "January, 08 2017 00:00:00",
            "country": "Egypt",
            "relevance": 2,
            "pestle": "Economic",
            "source": "EGYPS",
            "title": "The future success of the transformation of Egypt's oil and gas industry will further be related to the diversification of energy resources and liberalisation of the North Africa region's energy markets.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 6,
            "sector": "Energy",
            "topic": "gas",
            "insight": "US Dollar: Will It Impact Natural Gas Prices?",
            "url": "http://marketrealist.com/2017/01/us-dollar-will-impact-natural-gas-prices/",
            "region": "Northern America",
            "start_year": "",
            "impact": "",
            "added": "January, 15 2017 02:41:44",
            "published": "January, 12 2017 00:00:00",
            "country": "United States of America",
            "relevance": 3,
            "pestle": "Industries",
            "source": "marketrealist",
            "title": "Natural gas prices could develop a relationship with the US Dollar Index that's similar to the relationship between crude oil and the US Dollar Index.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 2,
            "sector": "",
            "topic": "",
            "insight": "Our Planet: The Environmental Dimension of the 2030 Agenda",
            "url": "http://apps.unep.org/publications/index.php?option=com_pub&task=download&file=012101_en",
            "region": "Central America",
            "start_year": "",
            "impact": "",
            "added": "July, 06 2016 03:51:54",
            "published": "May, 13 2016 00:00:00",
            "country": "Belize",
            "relevance": 1,
            "pestle": "",
            "source": "UNEP",
            "title": "The Belize barrier reef is under threat from overfishing.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 2,
            "sector": "",
            "topic": "",
            "insight": "Our Planet: The Environmental Dimension of the 2030 Agenda",
            "url": "http://apps.unep.org/publications/index.php?option=com_pub&task=download&file=012101_en",
            "region": "World",
            "start_year": "",
            "impact": "",
            "added": "July, 06 2016 03:51:53",
            "published": "May, 13 2016 00:00:00",
            "country": "",
            "relevance": 1,
            "pestle": "",
            "source": "UNEP",
            "title": "Almost half of all natural World Heritage sites are threatened by harmful industrial activities and operations.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 2,
            "sector": "Energy",
            "topic": "oil",
            "insight": "Britain's Plummeting Pound Is Bad News for America",
            "url": "http://foreignpolicy.com/2016/07/05/britains-plummeting-pound-is-bad-news-for-america/",
            "region": "",
            "start_year": "",
            "impact": "",
            "added": "July, 06 2016 01:54:35",
            "published": "July, 05 2016 00:00:00",
            "country": "",
            "relevance": 1,
            "pestle": "Industries",
            "source": "Foreign Policy",
            "title": "The continued fallout from Brexit could keep oil prices lower for longer.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 4,
            "sector": "Energy",
            "topic": "oil",
            "insight": "U.S. has more untapped oil than Saudi Arabia or Russia",
            "url": "http://money.cnn.com/2016/07/05/investing/us-untapped-oil/index.html",
            "region": "Northern America",
            "start_year": "",
            "impact": "",
            "added": "July, 06 2016 01:26:08",
            "published": "July, 05 2016 00:00:00",
            "country": "United States of America",
            "relevance": 2,
            "pestle": "Industries",
            "source": "CNNMoney",
            "title": "The U.S. could shoulder even more of the weight of global oil production in the future.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": "",
            "sector": "Energy",
            "topic": "oil",
            "insight": "Nomura's Kwan Sees Big Data Among Game Changers in Oil, Gas Industry",
            "url": "http://www.rigzone.com/news/oil_gas/a/145268/Nomuras_Kwan_Sees_Big_Data_Among_Game_Changers_in_Oil_Gas_Industry/?all=HG2",
            "region": "",
            "start_year": 2016,
            "impact": "",
            "added": "July, 05 2016 02:16:13",
            "published": "June, 28 2016 00:00:00",
            "country": "",
            "relevance": 5,
            "pestle": "Environmental",
            "source": "Rigzone",
            "title": "Exploration in deepwater and ultra-deepwater is not expected anytime soon despite signs that oil prices could reach $70 per barrel by end of 2016.",
            "likelihood": ""
        },
        {
            "end_year": "",
            "intensity": 2,
            "sector": "Energy",
            "topic": "gas",
            "insight": "Nomura's Kwan Sees Big Data Among Game Changers in Oil, Gas Industry",
            "url": "http://www.rigzone.com/news/oil_gas/a/145268/Nomuras_Kwan_Sees_Big_Data_Among_Game_Changers_in_Oil_Gas_Industry/?all=HG2",
            "region": "",
            "start_year": "",
            "impact": "",
            "added": "July, 05 2016 02:16:13",
            "published": "June, 28 2016 00:00:00",
            "country": "",
            "relevance": 1,
            "pestle": "Social",
            "source": "Rigzone",
            "title": "Robots are being deployed in refineries and natural gas pipelines to investigate problems, toxic spills, oil spills or managing risk in hazardous areas.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 2,
            "sector": "",
            "topic": "",
            "insight": "Biogas buses are the green solution for cities",
            "url": "http://euinmyregion.blogactiv.eu/2016/07/04/biogas-buses-are-the-green-solution-for-cities/",
            "region": "Eastern Europe",
            "start_year": "",
            "impact": "",
            "added": "July, 05 2016 00:55:08",
            "published": "July, 04 2016 00:00:00",
            "country": "Poland",
            "relevance": 1,
            "pestle": "",
            "source": "Europe in My Region",
            "title": "Combustion of methane in buses could significantly improve air quality (especially in Poland).",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 2,
            "sector": "Energy",
            "topic": "oil",
            "insight": "Supergelators Could Make for More Effective Oil Spill Cleanup",
            "url": "http://insights.globalspec.com/article/2880/supergelators-could-make-for-more-effective-oil-spill-cleanup?from_rss=1",
            "region": "",
            "start_year": "",
            "impact": "",
            "added": "July, 04 2016 02:06:29",
            "published": "June, 30 2016 00:00:00",
            "country": "",
            "relevance": 1,
            "pestle": "Environmental",
            "source": "IHS Engineering 360",
            "title": "Newly developed supergelators could help clean oil spills more efficiently and avoid the secondary pollution associated with some alternative cleanup methods.",
            "likelihood": 2
        },
        {
            "end_year": "",
            "intensity": 3,
            "sector": "Energy",
            "topic": "oil",
            "insight": "Advances in energy-storage technology, burgeoning electric car market driving lithium and graphite uptake",
            "url": "http://www.engineeringnews.co.za/article/advances-in-energy-storage-technology-burgeoning-electric-car-market-driving-lithium-and-graphite-uptake-2016-07-01",
            "region": "",
            "start_year": "",
            "impact": "",
            "added": "July, 04 2016 01:36:39",
            "published": "July, 01 2016 00:00:00",
            "country": "",
            "relevance": 1,
            "pestle": "Economic",
            "source": "Engineering News",
            "title": "The low price of oil is leading to questions about the projected high demand for EV sales.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 2,
            "sector": "Financial services",
            "topic": "oil",
            "insight": "Global oil demand to slow in 2016: IEA",
            "url": "http://www.cnbc.com/2015/07/10/global-oil-demand-to-slow-in-2016-iea.html",
            "region": "",
            "start_year": "",
            "impact": "",
            "added": "July, 03 2016 06:00:29",
            "published": "July, 10 2015 00:00:00",
            "country": "",
            "relevance": 1,
            "pestle": "Economic",
            "source": "CNBC ",
            "title": "A possible Greek exit from European Monetary Union (euro zone) could dampen not only Greek oil product demand, but also potentially curb deliveries across the continent if macro-economic activity were to weaken.",
            "likelihood": 2
        },
        {
            "end_year": 2016,
            "intensity": "",
            "sector": "Manufacturing",
            "topic": "growth",
            "insight": "IEA Says Oil Prices May Fall Even Further Before Supply Fades in 2016",
            "url": "http://www.bloomberg.com/news/articles/2015-07-10/iea-says-oil-price-may-fall-further-before-supply-fades-in-2016",
            "region": "Northern America",
            "start_year": "",
            "impact": "",
            "added": "July, 03 2016 06:00:25",
            "published": "July, 10 2015 00:00:00",
            "country": "United States of America",
            "relevance": 4,
            "pestle": "Economic",
            "source": "Bloomberg Business",
            "title": "U.S. production growth will slow to 300,000 barrels day next year from 900,000 a day in 2015.",
            "likelihood": ""
        },
        {
            "end_year": "",
            "intensity": 16,
            "sector": "",
            "topic": "growth",
            "insight": "IEA Says Oil Prices May Fall Even Further Before Supply Fades in 2016",
            "url": "http://www.bloomberg.com/news/articles/2015-07-10/iea-says-oil-price-may-fall-further-before-supply-fades-in-2016",
            "region": "",
            "start_year": 2016,
            "impact": "",
            "added": "July, 03 2016 06:00:25",
            "published": "July, 10 2015 00:00:00",
            "country": "",
            "relevance": 4,
            "pestle": "Economic",
            "source": "Bloomberg Business",
            "title": "Non-OPEC supply growth is expected to grind to a halt in 2016.",
            "likelihood": 4
        },
        {
            "end_year": 2016,
            "intensity": 3,
            "sector": "Retail",
            "topic": "export",
            "insight": "IEA Says Oil Prices May Fall Even Further Before Supply Fades in 2016",
            "url": "http://www.bloomberg.com/news/articles/2015-07-10/iea-says-oil-price-may-fall-further-before-supply-fades-in-2016",
            "region": "",
            "start_year": "",
            "impact": "",
            "added": "July, 03 2016 06:00:23",
            "published": "July, 10 2015 00:00:00",
            "country": "",
            "relevance": 1,
            "pestle": "Economic",
            "source": "Bloomberg Business",
            "title": "There will be no overall production growth outside the Organization of Petroleum Exporting Countries next year for the first time since 2008.",
            "likelihood": 3
        },
        {
            "end_year": "",
            "intensity": 2,
            "sector": "",
            "topic": "",
            "insight": "Greenhouse gas",
            "url": "https://en.wikipedia.org/wiki/Greenhouse_gas",
            "region": "World",
            "start_year": "",
            "impact": "",
            "added": "July, 03 2016 05:28:48",
            "published": "July, 03 2016 00:00:00",
            "country": "",
            "relevance": 1,
            "pestle": "",
            "source": "Wikipedia",
            "title": "Earth's surface temperature could exceed historical values as early as 2047.",
            "likelihood": 2
        }
    ]